[package]
name = "tcp_proxy"
version = "0.1.0"
authors = ["chenej <chenej@gzyitop.com>"]

[dependencies]
futures = "*"
tokio-core = "*"
tokio-io   = "*"
error-chain = "*"
toml = "*"
serde = "*"
serde_derive = "*"
uuid = {version = "*", features = ["v4", "v5"]}


[lib]
name = "tcp_proxy"
